#!/bin/bash
# This is a simple build script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

# Install databank-mongodb and forever, not in package.json
pushd ${OPENSHIFT_REPO_DIR}
    if [ ! -d node_modules/databank-mongodb/ ]; then
        npm install databank-mongodb
    fi
popd
# Generate config file for openshift if it doesn't already exist
${OPENSHIFT_REPO_DIR}/.openshift/lib/gen_openshift_pump_config.js

# Make uploaddir if it doesn't exist already
if [ ! -d ${OPENSHIFT_DATA_DIR}/uploads/ ]; then
    mkdir ${OPENSHIFT_DATA_DIR}/uploads/
fi
