language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
script: "npm test"
before_script:
  - "./test/hosts.sh"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq graphicsmagick
 - npm install shelljs
 - pwd
 - /home/travis/build/profOnno/pump.io/puu.js setupPackageJSON

